### ISSUE TITLE
txtp - Transition Music Segments Additional Info.

### ISSUE THREAD

**Issue by FenrisVN** [bnnm/wwiser#27]
Hello. Is there a way to add additional info to txtps for transition music segments? Like source and destination states ids (or any-to-any, any-to-none), sync info (immediate, next bar, etc), all that's included in AKTransitionRules? I know I can look for all this in bnk viewer, but getting all this info in txtp would save a lot of time and effort to recreate the music. No rush, no priority, just a humble request.

**Comment by bnnm** [comment]
Part of the src/dst info is included in the simplified tree comment (look for '>'), that could give you a start. As for sync info, it's typically only used in switch transitions and wwiser's txtp can't quite simulate switch changes, so not sure if they would be that useful, given switch lists tend to be huge. I'll give it some thought.

If you mean including it in the txtp (vgmstream) part itself, the ultimate goal is for vgmstream to fully recreate the music itself (including stuff like transitions), but it'll still take time since it depends on internal to handle more complex wwise features.

**Comment by FenrisVN** [comment]
I'll provide an example to show what I mean as I may be bad with words. I'm using wwiser and generated txtp to recreate some music in a DAW for my own listening pleasure. The soundbank are complex and have more than 100 objects, from 2 to 15 switches and some transitions. To add the corresponding transition segments (and place them accordingly) I use WWiser's bank viewer. Here's a rather simple bnk I'll use as an example.

![01](https://user-images.githubusercontent.com/130893477/234944696-8b6d396f-eb34-4c8b-8072-cded6eda38b5.jpg)

The CAKMusicSwitchCntr object has all the transitions rules between switch states.

![02](https://user-images.githubusercontent.com/130893477/234945518-5cf536c4-369f-4784-8a19-367458c248cb.jpg)

Here is one transition rule that lists SrcID (742159777), DestID (231040339) and their Rules (like transition time, fade curve, sync type (next bar here) and the transition MusicSegment used (958370226). 

![03](https://user-images.githubusercontent.com/130893477/234947637-93815e31-95f5-4861-a802-c3193449177e.jpg)

Now in AkDecisionTree we can see that SrcID (742159777) correspond to keys 0 (any) and 1281810935 (named start), DestID (231040339) corresponds to key 1100754038 (named alt) (I've found out a lot of WWiseID's names using your tools, so thanks for that!).
So that transition rule applies when the music transitions from any switch state and from "start" switch state explicitly, but to get this info I have to examine the soundbank through and through to find the corresponding keys and IDs as there may be many switch states, transition segments and transition rules.

The generated txtp for switch state "alt" (I'll attach it) has only this info:

PATH
#   CAkEvent[71] 3135830418
#   - hashname: public_event_glimmer_start
#
#     CAkActionPlay[70] 626678983
#
#       CAkMusicSwitchCntr[66] 89610811
#       ~ [music_switch=alt]
#
#         CAkMusicRanSeqCntr[22] 231040339
#         > any to any: post-exit ~ pre-entry

So, no transition time, no sync type, no transition segment info.

What I would like (if that's not too much) and what would make my work A LOT easier if I could either see the corresponding switch state names (keys) in transition rules right next to SrcIDs and DestIDs in WWiser's Bank Viewer, or have the transition info (time, sync type, transition segment) in generated txtp.

Of course, that's just a humble request, I understand the complexcity of WWise and that WWiser is a made substitute that can't do all the things WWise does, and still I am amazed by the work you've done. So if there's a way I can support you in any way, I'd gladly do so.

[public_event_glimmer.zip](https://github.com/bnnm/wwiser/files/11346601/public_event_glimmer.zip)

**Comment by bnnm** [comment]
I get the info you mean, but not sure how you mean to present it -- an example of how text could be printed in the txtp/comment would be more helpful. Seems rather clunky/huge to me but maybe you have a more concise idea.

Since src/dst point to other object's ids and not actual wems, writting them in the txtp itself doesn't seem to help you that much (you'd also have to check the bnk). Given how wwiser's txtp maker is designed (follows paths of current variables simulating as if they were playing; 742159777 doesn't participate in the current txtp so it's ommited) and how complex wwise can get, it'd be hard to get the output wem based on a random object src/dst. I think for your use case you'd be better off with a simplified bnk view/output or such tailored to see only relevant fields and transitions.

Note that comment tree is meant to be a reference to navigate the bnk, so when it prints `CAk* [123] 456` it should be easy enough to find HIRC [123] of id 456 in the viewer.

**Comment by FenrisVN** [comment]
Well, I've thought for a long time about a way to present the info I need, but, to be honest, given the complexity of wwise and after thoroughly examining the bnks and txtp outputs I can't think of a way to do that, especially with the complex paths to from Event ids to Center ids to CAKMusicSegments ids and then to MusicTracks ids and finally wems. And I've got a little more experience examining the bnks, so I can find the needed info much faster. So I think. for now, we'd better close this issue. If I'll come up with a good idea I'll let you know. And thank you for your hard work, a wonderful set of wwise tools and your willingless to listen and make it even better.
