### ISSUE TITLE
Event-Based Packaging (AkAssetPlatformData and AkMediaAsset) support

### ISSUE THREAD

**Issue by LBPHaxMods** [bnnm/wwiser#29]
Not sure if this is within the scope of wwiser, but Hello Neighbor VR (and probably other UE4 games) doesn't use .bnk files, but rather use .uasset files, and have a different folder structure from some other games using Wwise (i.e. FNAF Security Breach, Sackboy: A Big Adventure) 
![image](https://github.com/bnnm/wwiser/assets/92583355/abd92cb5-1f82-4fd6-84c1-914a089c264b)
![image](https://github.com/bnnm/wwiser/assets/92583355/a7e76c6f-dd9c-4642-a781-05932a429e73)
![image](https://github.com/bnnm/wwiser/assets/92583355/36a67d6b-42c4-4264-bbb4-683d7472f06e)

**Comment by bnnm** [comment]
You'd need to ask FModel's devs to properly extract .bnk/wem from uassets since it's a generic Unreal Engine format, then they can be loaded normally by wwiser.

Here is a modified UModel/UEViewer by [Nicknine](https://github.com/NicknineTheEagle/UEViewer) that supports those and extract them in a usable structure (then you can load the base folder containing all bnks with latest wwiser): [umodel.zip](https://github.com/bnnm/wwiser/files/12841004/umodel.zip)

You could use this to manually extract bnk as well bnk: https://github.com/bnnm/wwiser-utils/blob/master/scripts/bkhd_extractor.bms

Note that event names are found and used from the exported paths (at least as extracted by UModel) but bnk names are (I believe) some derived GUID so not reversable.
