### ISSUE TITLE
Can he be used as a module in python?

### ISSUE THREAD

**Issue by Virace** [bnnm/wwiser#30]
hi bro, I found that it seems not possible to use wwiser as a module after reviewing the source code. Will you provide an update in the future? 

That's what I want to do.
bnk files can be obtained from other files but not written to disk, but directly read in memory. The information parsed from the file can also be directly returned by the function for other operations.

**Comment by bnnm** [comment]
Not possible sorry, and updating it as a module is very unlikely as it would take time to adapt and keep the API stable, but there would be almost no users so not worth the effort.

Besides the internals only really make sense for this tool (I made them to be very easy/fast to code and tweak as needed, rather than something clean/stable) so I'd recommend using it as a learning tool instead.

You could dump the .bnk info to XML with this tool and read that XML for your purposes.

**Comment by Virace** [comment]
All right. Thanks.
