### ISSUE TITLE
Duplicate detection when processing multiple bnk files

### ISSUE THREAD

**Issue by lihaohong6** [bnnm/wwiser#49]
I ran the following commands to export `bnk` files as `txtp` files.

```shell
python wwiser.pyz -g -go txtp1 f1.bnk f2.bnk
```

```shell
python wwiser.pyz -g -go txtp2 f1.bnk
python wwiser.pyz -g -go txtp2 f2.bnk
```

`txtp1` and `txtp2` are expected to have the same content. However, `txtp1` has less files because (I would assume) some are marked as duplicates and never exported. My export workflow, which invokes `vgmstream-cli` to generate `wav` files from `txtp` files, ended up with a few missing files in the end because of this behavior. 

I'm not sure how to troubleshoot this. I'm guessing wwiser is persisting the duplication database across bnk files and mistakenly marking some as duplicates?

The bnk files are attached in case you need them to reproduce. [bnk.zip](https://github.com/user-attachments/files/18273722/Downloads.zip)

**Comment by bnnm** [comment]
wwiser marks duplicates based on resulting .txtp regardless of bnk origin. This is because it's common to repeat similar events in different banks that point to the same audio. For example f1-0033-event and f2-0020-event both use the same `.wem`. Not marking them dupes would be confusing I think ("these 2 txtp sound exactly the same to me, are they really different?").

I guess you want that duplicates in different banks are generated instead of marked as dupe. It would be technically possible to add some option but not sure if you really need that. You'll end up with repeated `.wav` just with different event names. 

You could also use `*.bnk -m -g` to get the same results as calling one by one, though it wouldn't allow using init.bnk with others.

(also see: https://github.com/bnnm/wwiser/blob/master/doc/WWISER.md#dupes-and-name-order).

**Comment by bnnm** [comment]
That's more or less correct. wwiser is designed so that if you load every bank it'll output every "usable" .txtp just once. But .txtp and dupes depend on the load order and other factors so names may not be the "nicer" ones, since there is no "correct" order from Wwise's perspective (bnk order it's up to devs).

More exactly it writes named events (from wwnames.txt) alphabetically first then unnamed events. For events with states (var=value) it'll sort them alphabetically too, except "none" (var=-) that goes first.

There are ways to force wwiser prioritize certain names, a bit clunky but couldn't think of anything usable: [here](https://github.com/bnnm/wwiser/blob/master/doc/WWISER.md#sort-always), [here](https://github.com/bnnm/wwiser/blob/master/doc/WWISER.md#sort-weight-param-weight), [this](https://github.com/bnnm/wwiser/blob/master/doc/WWISER.md#passing-filters) + *generate rest* explained below.
